### ISSUE TITLE
Twitter t.co GO TO HELL

### ISSUE THREAD

**Issue by samerali2** [GarrisonBaird/GreasyForkScripts#1]
![hmmm](https://user-images.githubusercontent.com/70457/28746907-02297324-7494-11e7-9180-e0bc009e1ba1.PNG)

maybe removing the ";" after the "}"
I know nothing about scripting :p

**Comment by GarrisonBaird** [comment]
You are right, though this extra ";" won't have any effect, script will still work, but thanks!
